USE [master]
GO

CREATE DATABASE [SmashDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SmashDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SmashDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SmashDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SmashDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SmashDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SmashDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SmashDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SmashDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SmashDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SmashDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SmashDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [SmashDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SmashDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SmashDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SmashDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SmashDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SmashDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SmashDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SmashDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SmashDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SmashDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SmashDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SmashDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SmashDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SmashDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SmashDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SmashDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SmashDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SmashDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SmashDB] SET  MULTI_USER 
GO
ALTER DATABASE [SmashDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SmashDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SmashDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SmashDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SmashDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SmashDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SmashDB] SET QUERY_STORE = OFF
GO
USE [SmashDB]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EntryExitTransactions](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NumberPlate] [nchar](10) NOT NULL,
	[EntryInterchangeId] [int] NULL,
	[EntryDateTime] [datetime] NULL,
	[ExitInterchangeId] [int] NULL,
	[ExitDateTime] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Interchanges](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](10) NOT NULL,
	[Distance] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET IDENTITY_INSERT [dbo].[Interchanges] ON 

INSERT [dbo].[Interchanges] ([Id], [Name], [Distance]) VALUES (1, N'Zero Point', 0)
INSERT [dbo].[Interchanges] ([Id], [Name], [Distance]) VALUES (3, N'NS        ', 5)
INSERT [dbo].[Interchanges] ([Id], [Name], [Distance]) VALUES (4, N'Ph4       ', 10)
INSERT [dbo].[Interchanges] ([Id], [Name], [Distance]) VALUES (5, N'Ferozpur  ', 17)
INSERT [dbo].[Interchanges] ([Id], [Name], [Distance]) VALUES (6, N'LakeCity  ', 24)
INSERT [dbo].[Interchanges] ([Id], [Name], [Distance]) VALUES (7, N'Raiwand   ', 29)
INSERT [dbo].[Interchanges] ([Id], [Name], [Distance]) VALUES (8, N'Bahria    ', 34)
SET IDENTITY_INSERT [dbo].[Interchanges] OFF
GO
USE [master]
GO
ALTER DATABASE [SmashDB] SET  READ_WRITE 
GO
